### ISSUE TITLE
Code Cleanup: Removing Redundant Dependencies

### ISSUE THREAD

**Issue by msulliva72** [mathworks/widgets-toolbox#28]
Per followup email:
	○ Adjust BackgroundColorable for objects (see SliderSpinner for example)
	○ Update BaseWidget to inherit BackgroundColorable
	○ Remove GridOrganized mixin and have each widget have their own internal grid
	○ Add copyright text to any new files, and set date to 2022
	○ Remove ErrorHandling mixin from objects that don't need it (not FileSelector/BaseWidget)
	○ Remove property accessors referencing BaseWidget when it inherits from ComponentContainer
	○ Replace RequestUpdate() with generic update() for ListSelector widgets

**Comment by rjackey** [comment]
It would be helpful to go through and compare the before/after behavior of each widget. I attempted this by saving off an old copy of WidgetExamples.mlx and view it alongside the current version in a new run.  

These are some issues uncovered:

1. Noted that the Grid property is now public in ButtonGrid, but it was not before.
2. May need another mixin to configure property display in the command window.  Only properties of the concrete class are being displayed by default, which is a change from the old release.  For example, ButtonGrid no longer shows ButtonColor, ButtonEnable, etc. This is important as it's how most users figure out how to tweak settings.
3. CheckboxList has a different background color from before (unsure which was correct)
4. ColorSelector and many other widgets seem to have more/different border around it than before
6. Not sure if it's a bug, but DateTimeSelector doesn't seem to honor the DateFormat in display.  Only shows when being edited.
